
name: kg_kaktus

# A title for display in the UI:
description: 'Scraping of Kaktus.media Website'

# Uncomment to run this scraper automatically:
# schedule: weekly
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: kg_kaktus.kg_kaktus_fetch:fetch_links
    handle:
      pass: parse

  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: kg_kaktus.kg_kaktus_parse:extract_data
    handle:
      store: store
      download: download

  download:
    method: kg_kaktus.kg_kaktus_download:download
    handle:
      pass: pass


  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "kg_kaktus"
      unique: 'title'
      children:
      -
        key: images
        table_suffix: images
        unique: 'image_url'

      - key: comments
        table_suffix: comments
        unique: 'comment_text'

      - key: tag_list
        table_suffix: tag_list
        unique: 'tag_name'