
name: kg_kse

# A title for display in the UI:
description: 'Scraping of kse.kg Website'

# Uncomment to run this scraper automatically:
# schedule: weekly
pipeline:

  init:
    # This first stage will get the ball rolling with a seed URL.
    method: kg_kse.kg_kse_fetch:fetch_pages_links
    handle:
      pass: fetch

  fetch:
    method: kg_kse.kg_kse_fetch:fetch_page_link
    handle:
      pass: parse


  parse:
    # Parse the scraped pages to find if they contain additional links.
    method: kg_kse.kg_kse_parse:extract_data
    handle:
      store: store
      download: download

  download:
    method: kg_kse.kg_kse_download:download
    handle:
      pass: pass

  store:
    # Store the crawled documents to a directory
    method: db
    params:
      table: "kg_kse"
      children:
      -
        key: reports
        table_suffix: reports

      - key: news_info
        table_suffix: news_info